baseUrl: "https://diti.me/"
title: "Diti [dot] me"
theme: "ditiv1"

params:
  ghrepo: "https://github.com/Diti/diti.me"

enableGitInfo: true

copyright: "Â© Dimitri â€œDitiâ€ Torterat"

# i18n
EnableMissingTranslationPlaceholders: true
languages:
  en:
    languageCode: "en"
    languageName: "ğŸ‡¬ğŸ‡§ English"
    permalinks:
      character: "/char/:title/"
  fr:
    languageCode: "fr"
    languageName: "ğŸ‡«ğŸ‡· FranÃ§ais"
    permalinks:
      character: "/perso/:title/"

permalinks:
  page: "/:title/"
  post: "/post/:title/"
  read: "/read/:title/"

# Cosmetic & internal settings
enableGitInfo: true

blackfriday:
  smartypants: false
  fractions: false
  smartDashes: false
  plainIDAnchors: true
canonifyUrls: true
footnoteAnchorPrefix: "note-"
footnoteReturnLinkContents: "â†©"
metadataFormat: "yaml"
pygmentscodefences: true
pygmentsuseclasses: true

outputs:
  home: ["HTML", "RSS"]
  page: ["HTML"]
  section: ["HTML", "RSS"]
  taxonomy: ["HTML", "RSS"]
