baseUrl: "https://diti.me/"
title: "Diti [dot] me"
theme: "ditiv1"

params:
  ghrepo: "https://github.com/Diti/diti.me"

enableGitInfo: true

copyright: "{year} Â© Dimitri â€œDitiâ€ Torterat"

# i18n
EnableMissingTranslationPlaceholders: true
languages:
  en:
    languageCode: "en"
    languageName: "ğŸ‡¬ğŸ‡§ English"
  fr:
    languageCode: "fr"
    languageName: "ğŸ‡«ğŸ‡· FranÃ§ais"

permalinks:
  character: "/char/:title/"
  page: "/:title/"
  post: "/post/:title/"
  read: "/read/:title/"

taxonomies:
  tag: "tags"
  category: "categories"

# Cosmetic & internal settings
enableGitInfo: true

blackfriday:
  smartypants: false
  fractions: false
  smartDashes: false
  plainIDAnchors: true
canonifyUrls: true
footnoteAnchorPrefix: "note-"
footnoteReturnLinkContents: "â†©"
metadataFormat: "yaml"
pygmentscodefences: true
pygmentsuseclasses: true

outputs:
  home: [ "HTML", "RSS" ]
  page: [ "HTML" ]
